version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - docker build -t ecs-demo:latest .
      - docker tag ecs-demo:latest 808364554647.dkr.ecr.us-east-1.amazonaws.com/ecs-demo:latest
  post_build:
    commands:
      - docker push 808364554647.dkr.ecr.us-east-1.amazonaws.com/ecs-demo:latest
      - printf '[{"name":"ecs-demo-hello-world","imageUri":"%s"}]' 808364554647.dkr.ecr.us-east-1.amazonaws.com/ecs-demo:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
